### ISSUE TITLE
Supported mods, now and plans?

### ISSUE THREAD

**Issue by xenoflot** [jaredlll08/CraftTweaker#128]
Hi Jared,

I was wondering if there are any supported mods that are not on the MT3 wiki (other than JEI).

My specific area of interest is mods with grinders. We need to crush AE2's certus and fluix into dusts but don't have any mods that provide compatible grinders out of the box. 

We do have ActuallyAdditions, TechReborn and ExtraUtils2 that provide grinders but they're not on the MT3 compatibility list.

Thanks!

**Comment by jaredlll08** [comment]
Modtweaker HAD support for AE2 but it was removed, look at the latest
modtweaker changelogs to see why, and no I will not add it back, at least
not without a damn good compelling reason.

On Jan 6, 2017 11:35, "xenoflot" <notifications@github.com> wrote:

Hi Jared,

I was wondering if there are any supported mods that are not on the MT3
wiki (other than JEI).

My specific area of interest is mods with grinders. We need to crush AE2's
certus and fluix into dusts but don't have any mods that provide compatible
grinders out of the box.

We do have ActuallyAdditions, TechReborn and ExtraUtils2 that provide
grinders but they're not on the MT3 compatibility list.

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jaredlll08/CraftTweaker/issues/128>, or mute the thread

**Comment by jaredlll08** [comment]
you know, reading your thing, makes much more sense, but I haven't actually played mc besides for testing in months, so I don't know new mods, so I'm not the person to ask for that.

For supported mods, CrT is getting no more mod support at this moment, the only reason it has JEI and IC2 support was because they were grandfathered in.
Now for Modtweaker, I really just add what I feel like adding, so I'm always open to suggestions

**Comment by xenoflot** [comment]
Yes, to clarify, by MT3 I meant MineTweaker3, not ModTweaker.

Basically we have a bunch of mods and CraftTweaker. As instructed, I'm using the MT3 wiki for information on how to script modifications. I'd like to be able to create a script to have one of the grinders support AE2 crystals to dust.

Based on the mod list on the MT3 wiki though, I wasn't sure if CraftTweaker supports the more recent mods out-of-the-box.

@Ommina Thanks for that. I don't have ModTweaker in our pack at the moment, but I'll add it to the testing setup and see if that works. If it does, perfect and I'll report back here for posterity.

Cheers
