### ISSUE TITLE
[1.10.2] Problems with JEI.hide script

### ISSUE THREAD

**Issue by Araton10** [jaredlll08/CraftTweaker#134]
Hello, i tried to hide some items in JEI actually i tried to use this script:

mods.jei.JEI.hide(<minecraft:dirt>);

actualy this script is formed only by this line of code but doesen't work..
Im using CraftTweaker-1.10.2-3.0.16

**Comment by jaredlll08** [comment]
Update your Jei and crafttweaker.

And use the format I provided here!

On Jan 8, 2017 15:29, "Araton10" <notifications@github.com> wrote:

Hello, i tried to hide some items in JEI actually i tried to use this
script:

mods.jei.JEI.hide(minecraft:dirt);

actualy this script is formed only by this line of code but doesen't work..
Im using CraftTweaker-1.10.2-3.0.16

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jaredlll08/CraftTweaker/issues/134>, or mute the thread
