### ISSUE TITLE
1.10.2 unresolvet JEI.hide problems

### ISSUE THREAD

**Issue by Araton10** [jaredlll08/CraftTweaker#135]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
Hello, i tried to update the version of JEI (Im using jei_1.10.2-3.14.2.401) end CraftTweaker-1.10.2-3.0.17.
Note: Im developing a modpack for server and the script i would to use only Server Side

#### What you expected to happen:
The items that i write in the script was hidden from JEI uploading the script only server side, in the older versions it work

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): http://pastebin.com/155kDqdq

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.10.2
- Forge: 1.10.2-12.18.3.2185
- CraftTweaker:-1.10.2-3.0.17

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
I'm a bit confused, are the scripts on both client and server?

**Comment by Araton10** [comment]
The script are only on Server side, for recipe it works, for Hide don't works, in client there aren't script

**Comment by jaredlll08** [comment]
Jei scripts NEED to be on both client and server.

**Comment by Araton10** [comment]
Ok, I'll try, I'm sorry for the ticket, in previous versions it worked just Server Side these scripts, with NEI

**Comment by jaredlll08** [comment]
NEI is NOT JEI, they are very different.

**Comment by Araton10** [comment]
I supposed that works, but i tried the script in the both in Server end Client but doesen't work, the script sintax is correct?

**Comment by jaredlll08** [comment]
Define doesn't work?

**Comment by Araton10** [comment]
I included the scripts in both the server and the client but the items continue to see each other

**Comment by jaredlll08** [comment]
What do you mean they continue to see each other?

**Comment by Araton10** [comment]
I mean that in the JEI i can seen the items that i have included in the script

**Comment by jaredlll08** [comment]
And both client and server have the exact same scripts? Are you reloading
the game or using mt reload?

**Comment by Araton10** [comment]
Both client and server have the same script, and i restart every time the server and the client

**Comment by jaredlll08** [comment]
Ok, just use the hiding ability in JEI, no need to use the minetweaker one

**Comment by Araton10** [comment]
It may be that at the beginning of the script is missing import mods.jei.JEI; ?
or the script was JEI.hide(<minecraft:ice> for example?


I did not know you could hide directly from the JEI

**Comment by jaredlll08** [comment]
The script is fine, the code behind it seems to be broken, but considering
that JEI has hiding, I'm gna remove my implementation

**Comment by Araton10** [comment]
Ok, I will inform me and I will use the JEI method, thanks for the support

**Comment by Araton10** [comment]
The function of the JEI is not usable in multiplayer, I beg you to consider to repair the broken code

**Comment by jaredlll08** [comment]
define it isn't usable in multiplayer?

**Comment by Araton10** [comment]
The JEI allows you to hide objects but it is only client side, the server does not work and is not safe for server administrators, because anyone can modify it at any time, the mod does not have a Config Server side showing the hidden objects

**Comment by Renari** [comment]
Simply hiding recipes isn't safe either, even if you hide it on both the server and the client, if they know the recipe they can craft it. You should use CraftTweaker to remove the recipes server side (thus making them uncraftable) and then use JEI to hide them client side (so that they don't clutter the JEI interface). Then players will be unable to see the recipe and be unable to craft said items.

**Comment by Yorkforce** [comment]
The problem is that JEI hiding is only client side, this creates alot of problems for modpack servers who can't change client files yet need to hide items in JEI because they are banned on the server. Even with recipes removed the item will still remain in JEI, this just causes confusion and frustration for player who gather items to try and craft a banned item only to find out its uncraftable.

I understand this may likely be a JEI issues and were fully aware JEI is not NEI, but if there is any possibility of JEI and CraftTweaker working together for some kind of solution this would be of huge help in bringing 1.10+ back inline with the functions of 1.7.
