### ISSUE TITLE
Oredict doesn't clear when reloading

### ISSUE THREAD

**Issue by TinkerWorX** [jaredlll08/CraftTweaker#142]
#### Intro:
When creating custom oredicts you might make mistakes. The current way CraftTweaker works forces you to restart the game if you make a mistake.

#### Issue Description:
When you reload a script, your custom oredicts aren't cleared. You'll have to remove each recipe individually to clear an oredict.

#### What happens:
Oredicts retain their added items when reloading. This is both visually with JEI and in crafting recipes.

#### What you expected to happen:
Oredicts should clear between reloads, since they will be cleared next time you load the game. This should only happen for custom oredicts. Alternatively, an oreDict.clear() method could be added which could be placed in the beginning of a script.

____
#### Affected Versions:

- Minecraft: 1.10.2
- Forge: 2202
- Crafttweaker: 1.10.2-3.0.17

**Comment by jaredlll08** [comment]
Are you trying to craft with the item or looking at the recipe in JEI?

**Comment by TinkerWorX** [comment]
Looking at the recipe in JEI. The item is still part of the oredict cycle when shown. I just tried when crafting, and it also still allowed me to use the recipe as well.

**Comment by darkhax** [comment]
Further testing is needed to confirm this issue. If I can confirm it in a dev environment we can get this fixed.

**Comment by WesCook** [comment]
I'd love to see this fixed, as it's causing the most issues in my pack currently.  If I can help test anything or provide a reproducable test case, please let me know.

**Comment by WesCook** [comment]
I just wanted to clarify, this is more than a visual glitch (as implied by the JEI desync comment in #162).  Even reloading the game will not correctly remove oredict entries.

Just as a visual example:

---

I created a recipe for jack o' lanterns that can use any `<ore:torch>`.

```
recipes.remove(<minecraft:lit_pumpkin>); // Jack o' lantern
recipes.addShapeless(<minecraft:lit_pumpkin>, [<minecraft:pumpkin>, <ore:torch>]);
```

Then I added `<ore:torch>` to various torch sources, and *removed* it from the Tinkers stone torches.

```
<ore:torch>.remove(<tconstruct:stone_torch>);
```

Yet a stone torch still works.  It never had the oredict entry removed.

![jackolantern](https://cloud.githubusercontent.com/assets/792101/23833248/31824f94-0700-11e7-9e32-7154a9ddf17e.png)
(not visual)

Removing oredict entries seems to fail completely in the current version.  Adding oredict entries is also inconsistent (sometimes it requires an `/mt reload`, even after a game restart), but that's less problematic.

This issue was mentioned in the closed #141, so I don't believe it's specific to me.  I can reproduce with only CraftTweaker installed.

**Comment by quixQuery** [comment]
Would like to vouch for this issue. Trying to remove ore dictionary values so different cobblestones (andesite cobble etc.) don't show up as valid grinder outputs, and the ore dictionary value is not being removed. I have tried with multiple mods and situations, and the ore dictionary still won't remove, though it doesn't show up with an error when scripts are loading, or reloading.

`val oreCobble = <ore:cobblestone>;

oreCobble.remove(<nethercore:stone:1>);`

**Comment by bookerthegeek** [comment]
As a workaround till if or when this is fixed, create a variable that includes the items you want to use in the recipe and then loop the recipe with that variable.
