### ISSUE TITLE
[1.11.2] Deprecate JEI.hide() function

### ISSUE THREAD

**Issue by SnowShock35** [jaredlll08/CraftTweaker#161]
Since the JEI hide function still continues to disappoint in CraftTweaker and JEI has the ability to do this anyway, it seems best to deprecate this function for 1.11 (Possibly 1.10 too). Therefore removing anymore issues on the matter. 

P.S. Don't forget to remove it from the wiki and make a note of it in the changelog

**Comment by Ommina** [comment]
If we're offering opinions, I disagree.  I'd far rather see .hide working than removed.

While I agree that removing it is better than a broken version, and since I'm not the one writing the code, I don't have any right to add to @jaredlll08's plate.  Nonetheless, I believe giving up on a scriptable .hide() would be a loss.

**Comment by SnowShock35** [comment]
You miss understand. 

I'd personally love this to be working feature to CraftTweaker, but in it's current state and Jared's statement on it in issue #135#issuecomment-271158810. It's fairly certain it'll be removed. I've just made a note of it for his memories sake.

**Comment by jaredlll08** [comment]
JEI.hide now works perfectly
