### ISSUE TITLE
CraftTweaker breaks /help

### ISSUE THREAD

**Issue by p455w0rd** [jaredlll08/CraftTweaker#80]
Since you're implementing ICommand, you're required to override the compareTo method. [MCServer.java#L150](https://github.com/jaredlll08/CraftTweaker/blob/master/MineTweaker3-MC1102-Main/src/main/java/minetweaker/mc1102/server/MCServer.java#L150). When you do this, but don't actually do the required comparison, it breaks the /help command. I would have submitted a PR, but it likely would have been denied, This is why I am posting here. 

This:
```java
	@Override
	public int compareTo(ICommand o)
	{
		return 0;
	}
```

Should be:
```java
	@Override
	public int compareTo(ICommand o)
	{
		return this.getCommandName().compareTo(o.getCommandName());
	}
```

**Comment by jaredlll08** [comment]
Never be scared to make a PR. I'm actually offended, by saying that a PR to me would have likely been denied, you are putting me on the same assholery level of Lex. the ONLY time I deny pull requests is if it is plain stupid (this is not), or if it could cause issues (this fixes issues).

Anyway, fixed in the java8 branch, thanks!

**Comment by p455w0rd** [comment]
Oh..i was saying that simply because of the size of the PR XD..nothing against you personally :)

**Comment by jaredlll08** [comment]
I'm fairly sure, somewhere down the line, I have accepted a 1 line change
PR, like I said, I don't care about who makes it, what it doe or how small
or big it is, if it works, then I'll accept

On Nov 5, 2016 9:56 PM, "p455w0rd" <notifications@github.com> wrote:

Oh..i was saying that simply because of the size of the PR XD..nothing
against you personally :)

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/jaredlll08/CraftTweaker/issues/80#issuecomment-258636703>,
or mute the thread
